### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by meciasbueno** [nickfrosty/nuxt-seo#8]
How do I use this lib? the documentation page is not working

https://nuxt-seo.frostbutter.com/

**Comment by nickfrosty** [comment]
@meciasbueno recently went through a server migration. Just fixed the issue with the docs site. It works now!

**Comment by meciasbueno** [comment]
> @meciasbueno recently went through a server migration. Just fixed the issue with the docs site. It works now!

Thanks
